/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupChar123DataChar125RouteImport } from './routes/setup.{-$data}'
import { Route as GameDataRouteImport } from './routes/game.$data'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupChar123DataChar125Route = SetupChar123DataChar125RouteImport.update({
  id: '/setup/{-$data}',
  path: '/setup/{-$data}',
  getParentRoute: () => rootRouteImport,
} as any)
const GameDataRoute = GameDataRouteImport.update({
  id: '/game/$data',
  path: '/game/$data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/$data': typeof GameDataRoute
  '/setup/{-$data}': typeof SetupChar123DataChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/$data': typeof GameDataRoute
  '/setup/{-$data}': typeof SetupChar123DataChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game/$data': typeof GameDataRoute
  '/setup/{-$data}': typeof SetupChar123DataChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game/$data' | '/setup/{-$data}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game/$data' | '/setup/{-$data}'
  id: '__root__' | '/' | '/game/$data' | '/setup/{-$data}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameDataRoute: typeof GameDataRoute
  SetupChar123DataChar125Route: typeof SetupChar123DataChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/{-$data}': {
      id: '/setup/{-$data}'
      path: '/setup/{-$data}'
      fullPath: '/setup/{-$data}'
      preLoaderRoute: typeof SetupChar123DataChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$data': {
      id: '/game/$data'
      path: '/game/$data'
      fullPath: '/game/$data'
      preLoaderRoute: typeof GameDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameDataRoute: GameDataRoute,
  SetupChar123DataChar125Route: SetupChar123DataChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
